// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuGuAdHeMttSZhPaKs-lmR3saQDcBIag',
    appId: '1:689508606161:web:3698de8ebd2f28f31fe5f0',
    messagingSenderId: '689508606161',
    projectId: 'my-project-b1aab',
    authDomain: 'my-project-b1aab.firebaseapp.com',
    storageBucket: 'my-project-b1aab.appspot.com',
    measurementId: 'G-J0N4CWSNVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVSn6_tGIYDlOwXTTczsRK3o_y5gaKpSI',
    appId: '1:689508606161:android:7d92315099ac7d3a1fe5f0',
    messagingSenderId: '689508606161',
    projectId: 'my-project-b1aab',
    storageBucket: 'my-project-b1aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOIZcIHdTRLrhrv2GStpG3cVlrxKNJyx4',
    appId: '1:689508606161:ios:a85c15521e1d838d1fe5f0',
    messagingSenderId: '689508606161',
    projectId: 'my-project-b1aab',
    storageBucket: 'my-project-b1aab.appspot.com',
    iosBundleId: 'com.example.responsive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOIZcIHdTRLrhrv2GStpG3cVlrxKNJyx4',
    appId: '1:689508606161:ios:0693d113680da74b1fe5f0',
    messagingSenderId: '689508606161',
    projectId: 'my-project-b1aab',
    storageBucket: 'my-project-b1aab.appspot.com',
    iosBundleId: 'com.example.responsive.RunnerTests',
  );
}
